### ISSUE TITLE
Melpa

### ISSUE THREAD

**Issue by elimirks** [abo-abo/matlab-mode#1]
Hello!

The package no longer shows up in Melpa :{

**Comment by abo-abo** [comment]
This is my personal fork, it's not intended to be on MELPA (especially since I haven't done anything in MATLAB for a year now).

See this file: https://github.com/melpa/melpa/blob/master/recipes/matlab-mode. It says that https://git.code.sf.net/p/matlab-emacs/src is the official matlab-mode repo.

**Comment by elimirks** [comment]
Aha, thanks!
