### ISSUE TITLE
After upgrading Matlab to 2018a version M-x matlab-shell stopped working

### ISSUE THREAD

**Issue by guilherme-salome** [abo-abo/matlab-mode#2]
I've been using matlab-mode to work with Matlab 2017a version for some time, but had to upgrade Matlab to 2018a. However, after doing so (and uninstalling 2017a, small hd), I can no longer start a matlab shell within emacs. Running `M-x matlab-shell` displays the message "Searching for program: No such file or directory, matlab".

How can I fix this?

Thanks for helping! :D

**Comment by abo-abo** [comment]
Make sure you can start `matlab` from console.

**Comment by guilherme-salome** [comment]
Thanks @abo-abo,  adding a symlink to the matlab binary solved my problem.

For future reference, if you are on Mac, then:
`sudo ln -s /Applications/MATLAB_2018a.app/bin/matlab /usr/bin/`
makes it so that the matlab binary can be found in terminal. However, adding a symlink to the `/usr/bin/` folder requires disabling `csrutil`, which has many drawbacks. To avoid this issue, add the symlink to `/usr/local/bin/`, which also make things work.
