### ISSUE TITLE
Stop execution of running code shortcut

### ISSUE THREAD

**Issue by averter** [abo-abo/matlab-mode#3]
Hi,

This must be an easy one. I love this emacs mode, but I feel lack of an essential shortcut to end a running MATLAB script. So far I had to do it by clicking on the STOP button at the top of the buffer menu. Is there such a shortcut or is it possible to configure one in .emacs? If so how? Thank you in advance

**Comment by abo-abo** [comment]
I'ts probably <kbd>C-c C-c</kbd> from the shell. I haven't used MATLAB for more than two years now, and I don't plan to use it in the future.

**Comment by averter** [comment]
It works. Thank you very much
